<a href="https://colab.research.google.com/github/neerajsingh9929/Machine-Learning-tutorial/blob/main/nullvaluesin_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded=files.upload()


Saving Titanicdataset.xlsx to Titanicdataset.xlsx


In [2]:
import pandas as pd
DF=pd.read_excel(uploaded['Titanicdataset.xlsx'])
DF


Class     Sex   Age Embarked  survived
0    3.0    Male  20.0        S       0.0
1    1.0  Female  16.0        C       1.0
2    3.0  Female   NaN        S       1.0
3    1.0  Female   NaN        S       1.0
4    3.0    Male   NaN        S       0.0

In [3]:
# DF. isnull(). $$ tell how many rows null in every tuple

DF.isnull().sum()

Class       0
Sex         0
Age         3
Embarked    0
survived    0
dtype: int64

In [4]:
#DF.drop('Age',axis='columns')
# null value wale column ko drap ker dega

In [5]:
DF['Age'].fillna(DF['Age'].mean(),inplace=True)  # inplace=>>>True means where inser data
DF

Class     Sex   Age Embarked  survived
0    3.0    Male  20.0        S       0.0
1    1.0  Female  16.0        C       1.0
2    3.0  Female  18.0        S       1.0
3    1.0  Female  18.0        S       1.0
4    3.0    Male  18.0        S       0.0

In [6]:
# DF.dropna()   # drop all data of where is null value


In [7]:
DF.drop('survived',axis='columns') 

y=DF['survived'].values  # converting in array
y

array([0., 1., 1., 1., 0.])

In [8]:
from sklearn.preprocessing import OneHotEncoder
Enc=OneHotEncoder(sparse=False)
Enc.fit_transform(DF[['Sex','Embarked']])

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.]])

In [9]:
from sklearn.compose import make_column_transformer

trans= make_column_transformer((OneHotEncoder(),['Sex','Embarked']),remainder='passthrough')
trans.fit_transform(DF)

array([[ 0.,  1.,  0.,  1.,  3., 20.,  0.],
       [ 1.,  0.,  1.,  0.,  1., 16.,  1.],
       [ 1.,  0.,  0.,  1.,  3., 18.,  1.],
       [ 1.,  0.,  0.,  1.,  1., 18.,  1.],
       [ 0.,  1.,  0.,  1.,  3., 18.,  0.]])

MIN MAX SCALLING USING PYTHON SKLEARN


In [10]:
from sklearn.preprocessing import MinMaxScaler
data=[[-1,2],[0.5,6],[0,10],[1,18]]
scaler=MinMaxScaler()
newdata=(scaler.fit(data))
newdata


MinMaxScaler()

varience= semetion{(x1-m)^2}/n



standerd derivation (sigma) =    (varience)^1/2

Principal componenets&&&&&&&&&&&&&



In [11]:
from sklearn.datasets import  load_iris
iris= load_iris()
x=iris.data
from sklearn.decomposition import PCA
pc=PCA(n_components=2)
x1=pc.fit_transform(x)
x1


array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425],
       [-2.50694709,  0.6450689 ],
       [-2.61275523,  0.01472994],
       [-2.78610927, -0.235112  ],
       [-3.22380374, -0.51139459],
       [-2.64475039,  1.17876464],
       [-2.38603903,  1.33806233],
       [-2.62352788,  0.81067951],
       [-2.64829671,  0.31184914],
       [-2.19982032,  0.87283904],
       [-2.5879864 ,  0.51356031],
       [-2.31025622,  0.39134594],
       [-2.54370523,  0.43299606],
       [-3.21593942,  0.13346807],
       [-2.30273318,  0.09870885],
       [-2.35575405, -0.03728186],
       [-2.50666891, -0.14601688],
       [-2.46882007,  0.13095149],
       [-2.56231991,  0.36771886],
       [-2.63953472,

k fold cross validation 
on regression 

In [12]:
from google.colab import files
uploaded=files.upload()


Saving plot price dataset.xlsx to plot price dataset.xlsx


In [13]:
import pandas as pd 
DF=pd.read_excel(uploaded['plot price dataset.xlsx'])
x=DF['plot Price']
y=DF['plot size']
import numpy as np
(n,)=np.shape(x)
x1=x.to_numpy()
y1=y.to_numpy()
 
x2=x1.reshape(n,1)
y2=y1.reshape(n,1)


In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
score=cross_val_score(LR,x2,y2,cv=4).mean()
score

0.6342296870018729